# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b7cb449b1de7280662bbf69a3ba46e817041aa69a6ed8d7304e632ad4b98b400588787f7e071fd2acae8e518016314c623df2ad738c1540ced4e39449e9d1f60

test:
  secret_key_base: 23dc85da2be58f2da39423950088c30917e2f504e0da2e88e4d96c720255c972e1e89c0b13af64135ce353d7616cc0d97b812b5584a5f8a52bc5e63274b77272

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
